### ISSUE TITLE
Can you publish apk？

### ISSUE THREAD

**Issue by imzf** [AyushR1/KernelAdiutor-Mod#2]
I don't know how to compile Android app. Can you release a compiled version?

**Comment by AyushR1** [comment]
https://androidfilehost.com/?fid=818070582850490285

**Comment by gargakshit** [comment]
@AyushR1 Kernel Auditor is too on play store!!!

**Comment by AyushR1** [comment]
@gargakshit He wanted the moded one😐

**Comment by gargakshit** [comment]
@AyushR1 Ohk

**Comment by imzf** [comment]
@AyushR1 thank you
